name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-test-notebooks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package and dev deps (incl. mne for EEG)
        run: |
          python -m pip install --upgrade pip
          # Project deps (editable install) and extras for tests/notebooks
          python -m pip install -e .
          # Repo requirements (e.g., obspy for seismic notebooks)
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          # CI tooling
          python -m pip install pytest pytest-cov nbconvert mne requests jupyter jupyter_client nbclient ipykernel traitlets tornado

      - name: Register IPython kernel
        run: |
          python -m ipykernel install --user --name python3 --display-name "Python 3 (CI)"

      - name: Run tests
        run: pytest -q

      - name: Cache MNE/EEG downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/.mne
            ~/mne_data
          key: ${{ runner.os }}-mne-${{ hashFiles('**/scripts/run_notebooks.sh', '**/notebooks/02_eeg_hazard_tiering.ipynb') }}
          restore-keys: |
            ${{ runner.os }}-mne-

      - name: Prefetch small datasets (IRIS + GWOSC)
        run: |
          IRIS_DURATION=60 bash scripts/fetch_all_data.sh || true
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'

      - name: Run notebooks (include EEG)
        run: |
          RUN_EEG=true bash scripts/run_notebooks.sh
        env:
          MPLBACKEND: Agg
          # Ensure Jupyter finds the user kernelspec path set above
          JUPYTER_PATH: ~/.local/share/jupyter

      - name: Convert notebooks to HTML artifacts
        run: |
          mkdir -p artifacts
          jupyter nbconvert --to html notebooks/02_eeg_hazard_tiering.ipynb --output-dir artifacts || true
          jupyter nbconvert --to html notebooks/03_photonics_octave_jumps.ipynb --output-dir artifacts || true
          jupyter nbconvert --to html notebooks/04_seismic_hazard_surrogates.ipynb --output-dir artifacts || true
        env:
          MPLBACKEND: Agg

      - name: Upload notebook artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notebook-html
          path: artifacts
