name: Notebooks

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'notebooks/**'
      - 'src/**'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install jupyter nbconvert
      - name: Execute notebooks (skip missing; longer timeout)
       run: |
         mkdir -p artifacts
         set -e
         for nb in \
           "notebooks/02_eeg_hazard_tiering.ipynb" \
           "notebooks/03_photonics_octave_jumps.ipynb" \
           "notebooks/04_seismic_hazard_surrogates.ipynb"
         do
           if [ -f "$nb" ]; then
             echo "Executing $nb"
             jupyter nbconvert \
               --to html --execute "$nb" \
               --ExecutePreprocessor.timeout=1200 \
               --output-dir artifacts
           else
             echo "SKIP: $nb (not found)"
           fi
         done
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notebook-reports
          path: artifacts
