name: Notebooks

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'notebooks/**'
      - 'src/**'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install jupyter nbconvert
      - name: Execute notebooks
        run: |
          mkdir -p artifacts
          jupyter nbconvert --to html --execute notebooks/02_eeg_hazard_tiering.ipynb --output-dir artifacts
          jupyter nbconvert --to html --execute notebooks/03_photonics_octave_jumps.ipynb --output-dir artifacts
          jupyter nbconvert --to html --execute notebooks/04_seismic_hazard_surrogates.ipynb --output-dir artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notebook-reports
          path: artifacts
