name: Notebooks (deprecated)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Notebooks are executed in CI
        run: |
          echo "This workflow is deprecated. Notebooks are executed and artifacts uploaded by .github/workflows/ci.yml."
